### PR TITLE
version 108.0.1462.38

### PR DESCRIPTION
**Pull request by lacell75**

### CODE REVIEW

**Comment by lacell75** [comment]
@soulgalore Could you merge it, please?

**Comment by soulgalore** [comment]
Hi @lacell75 yes sorry, I'll fix it today. I use the switch that removes the version check so I don't always upgrade to the latest version.

**Comment by soulgalore** [comment]
Rerun to see if the edgedrievr on Mac works.

**Comment by lacell75** [comment]
I udpated version . edgdriver works on MAC now.

**Pull request merged**
